name: Deploy package to pypi

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    
    - name: Install packaging dependencies
      run: pip install versioneer
    
    - name: Packaging
      working-directory: symmetryshift
      run: python setup.py sdist

    - name: Publish a distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: symmetryshift/dist
