name: Deploy web sample

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy function
      working-directory: web/function/
      run: | 
        gcloud functions deploy fetch_biological_assembly \
          --env-vars-file .env.yaml \
          --trigger-http \
          --runtime python39 \
          --allow-unauthenticated
