name: Deploy web sample

on:
  push:
    branches:
      - master

jobs:
  deploy-functions:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy function
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: fetch_biological_assembly
          runtime: python39
          source_dir: ./web/functions
          env_vars_file: ./web/functions/.env.yaml
          ingress_settings: ALLOW_ALL

  deploy-page:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.3'
      
      - name: install firebase-tools
        run: npm install firebase-tools
      
      - name: deploy page
        working-directory: web/
        run: firebase deploy --only hosting --token $FIREBASE_CI_TOKEN
        env:
          FIREBASE_CI_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
