name: Deploy web sample

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy function
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: fetch_biological_assembly
          runtime: python39
          source_dir: ./web/functions
          env_vars_file: .env.yaml
          event_trigger_type: http
          ingress_settings: all
